### ISSUE TITLE
The bar graph is painted with the background color and thus is invisible

### ISSUE THREAD

**Issue by Strunzdesign** [tuxmaster/QtDMM#2]
Hi,

I nearly finished the support for the Voltcraft VC870 multimeter in my branch :-) Please do not merge it yet, as to complete the frequency mode I have to get a frequency synthesizer from work first in order to fix scaling and the position of the decimal dot.

However, there is a problem with the display of the bar graph. In line 380 of file src/sources/displaywid.cpp the wrong color is selected: instead of using palette().window().color(), which is the background color, one has to use palette().windowText().color(). Otherwise you paint gray on gray ;-)

See:
https://github.com/Strunzdesign/QtDMM/commit/f75fea733a621be41eec741685611012128a6905

Feel free to change that in your branch, or just wait for my pull request as soon as I completed support for the frequency mode. Then you'll get that for free.

Regards,
Florian

**Comment by tuxmaster** [comment]
Included your fix from pull request :)
