### ISSUE TITLE
ut61e+ bluetooth adapter

### ISSUE THREAD

**Issue by kris0725pl** [tuxmaster/QtDMM#20]
hi, add support for bluetooth adapter for windows 0.9.6 cersion
https://meters.uni-trend.com/product/ut-d-series/

cant connect with ut61e+

**Comment by tuxmaster5000** [comment]
please create an PR for it.

**Comment by kris0725pl** [comment]
What is PR?

**Comment by kris0725pl** [comment]
I cant create pull request...sorry. I go search help any where.

**Comment by kris0725pl** [comment]
Thx
