### ISSUE TITLE
Original upstream changes

### ISSUE THREAD

**Issue by luigino** [tuxmaster/QtDMM#8]
I just wanted to know if there are plans to support Uni-Trend UT61B and UT61D and Metex-3840 as per post-fork 0.9.2 changes.

I'd create a PR myself but I don't know this code at all.

**Comment by luigino** [comment]
I hope this is good https://github.com/tuxmaster/QtDMM/pull/10

**Comment by tuxmaster** [comment]
When some one can test it with the devices, than I can merge the pull request.

**Comment by luigino** [comment]
I assume someone did. Have all the other supported devices likewise been tested?

**Comment by tuxmaster** [comment]
As far as I was get access to the devices at the porting project to Qt5.

**Comment by luigino** [comment]
All of them?:open_mouth:

**Comment by tuxmaster** [comment]
Not all. As I wrote: Only to which I get access. I think it was 10 devices.

**Comment by luigino** [comment]
My point is, if the original upstream added them,  shouldn't that be enough?
After all most of the supported devices have been grandfathered in.

**Comment by tuxmaster** [comment]
Done :)
